#pragma once

#ifndef _WIN32

#include "always.h"
#include <objbase.h>
#include <stdint.h>
#include <windows.h>

#ifdef __cplusplus
extern "C" {
#endif

// Forward declarations of interfaces
struct IDirect3D8;
struct IDirect3DDevice8;
struct IDirect3DResource8;
struct IDirect3DBaseTexture8;
struct IDirect3DTexture8;
struct IDirect3DCubeTexture8;
struct IDirect3DVolumeTexture8;
struct IDirect3DSurface8;
struct IDirect3DVolume8;
struct IDirect3DVertexBuffer8;
struct IDirect3DIndexBuffer8;
struct IDirect3DSwapChain8;

// #include "d3d8caps.h"
// #include "d3d8types.h"

typedef enum _D3DXIMAGE_FILEFORMAT {
  D3DXIFF_BMP = 0,
  D3DXIFF_JPG = 1,
  D3DXIFF_TGA = 2,
  D3DXIFF_PNG = 3,
  D3DXIFF_DDS = 4,
  D3DXIFF_PPM = 5,
  D3DXIFF_DIB = 6,
  D3DXIFF_HDR = 7,
  D3DXIFF_PFM = 8,
  D3DXIFF_FORCE_DWORD = 0x7fffffff
} D3DXIMAGE_FILEFORMAT;

typedef D3DXIMAGE_FILEFORMAT D3DIMAGE_FILEFORMAT;

typedef enum _D3DMULTISAMPLE_TYPE {
  D3DMULTISAMPLE_NONE = 0,
  D3DMULTISAMPLE_2_SAMPLES = 2,
  D3DMULTISAMPLE_3_SAMPLES = 3,
  D3DMULTISAMPLE_4_SAMPLES = 4,
  D3DMULTISAMPLE_5_SAMPLES = 5,
  D3DMULTISAMPLE_6_SAMPLES = 6,
  D3DMULTISAMPLE_7_SAMPLES = 7,
  D3DMULTISAMPLE_8_SAMPLES = 8,
  D3DMULTISAMPLE_9_SAMPLES = 9,
  D3DMULTISAMPLE_10_SAMPLES = 10,
  D3DMULTISAMPLE_11_SAMPLES = 11,
  D3DMULTISAMPLE_12_SAMPLES = 12,
  D3DMULTISAMPLE_13_SAMPLES = 13,
  D3DMULTISAMPLE_14_SAMPLES = 14,
  D3DMULTISAMPLE_15_SAMPLES = 15,
  D3DMULTISAMPLE_16_SAMPLES = 16,
  D3DMULTISAMPLE_FORCE_DWORD = 0xffffffff
} D3DMULTISAMPLE_TYPE;

typedef enum _D3DDEVTYPE {
  D3DDEVTYPE_HAL = 1,
  D3DDEVTYPE_REF = 2,
  D3DDEVTYPE_SW = 3,
  D3DDEVTYPE_FORCE_DWORD = 0xffffffff
} D3DDEVTYPE;

typedef struct _D3DADAPTER_IDENTIFIER8 {
  char Driver[512];
  char Description[512];
  LARGE_INTEGER DriverVersion;
  DWORD VendorId;
  DWORD DeviceId;
  DWORD SubSysId;
  DWORD Revision;
  GUID DeviceIdentifier;
  DWORD WHQLLevel;
} D3DADAPTER_IDENTIFIER8;

typedef enum _D3DPOOL {
  D3DPOOL_DEFAULT = 0,
  D3DPOOL_MANAGED = 1,
  D3DPOOL_SYSTEMMEM = 2,
  D3DPOOL_SCRATCH = 3,
  D3DPOOL_FORCE_DWORD = 0x7fffffff
} D3DPOOL;

typedef enum _D3DFORMAT {
  D3DFMT_UNKNOWN = 0,
  D3DFMT_R8G8B8 = 20,
  D3DFMT_A8R8G8B8 = 21,
  D3DFMT_X8R8G8B8 = 22,
  D3DFMT_R5G6B5 = 23,
  D3DFMT_X1R5G5B5 = 24,
  D3DFMT_A1R5G5B5 = 25,
  D3DFMT_A4R4G4B4 = 26,
  D3DFMT_R3G3B2 = 27,
  D3DFMT_A8 = 28,
  D3DFMT_A8R3G3B2 = 29,
  D3DFMT_X4R4G4B4 = 30,
  D3DFMT_D16_LOCKABLE = 70,
  D3DFMT_D32 = 71,
  D3DFMT_D15S1 = 73,
  D3DFMT_D24S8 = 75,
  D3DFMT_D24X4S4 = 79,
  D3DFMT_D24X8 = 77,
  D3DFMT_D16 = 80,
  D3DFMT_DXT1 = 0x31545844,
  D3DFMT_DXT2 = 0x32545844,
  D3DFMT_DXT3 = 0x33545844,
  D3DFMT_DXT4 = 0x34545844,
  D3DFMT_DXT5 = 0x35545844,
  D3DFMT_P8 = 41,
  D3DFMT_A8P8 = 40,
  D3DFMT_L8 = 50,
  D3DFMT_A8L8 = 51,
  D3DFMT_A4L4 = 52,
  D3DFMT_V8U8 = 60,
  D3DFMT_L6V5U5 = 61,
  D3DFMT_X8L8V8U8 = 62,
  D3DFMT_Q8W8V8U8 = 63,
  D3DFMT_V16U16 = 64,
  D3DFMT_W11V11U10 = 65,
  D3DFMT_UYVY = 0x59565955,
  D3DFMT_YUY2 = 0x32595559,
} D3DFORMAT;

#define D3DENUM_NO_WHQL_LEVEL 0x00000002L

typedef enum _D3DSWAPEFFECT {
  D3DSWAPEFFECT_DISCARD = 1,
  D3DSWAPEFFECT_FLIP = 2,
  D3DSWAPEFFECT_COPY = 3,
  D3DSWAPEFFECT_COPY_VSYNC = 4,
  D3DSWAPEFFECT_FORCE_DWORD = 0xffffffff
} D3DSWAPEFFECT;

typedef enum _D3DRESOURCETYPE {
  D3DRTYPE_SURFACE = 1,
  D3DRTYPE_VOLUME = 2,
  D3DRTYPE_TEXTURE = 3,
  D3DRTYPE_VOLUMETEXTURE = 4,
  D3DRTYPE_CUBETEXTURE = 5,
  D3DRTYPE_VERTEXBUFFER = 6,
  D3DRTYPE_INDEXBUFFER = 7,
  D3DRTYPE_FORCE_DWORD = 0x7fffffff
} D3DRESOURCETYPE;

typedef enum _D3DCUBEMAP_FACES {
  D3DCUBEMAP_FACE_POSITIVE_X = 0,
  D3DCUBEMAP_FACE_NEGATIVE_X = 1,
  D3DCUBEMAP_FACE_POSITIVE_Y = 2,
  D3DCUBEMAP_FACE_NEGATIVE_Y = 3,
  D3DCUBEMAP_FACE_POSITIVE_Z = 4,
  D3DCUBEMAP_FACE_NEGATIVE_Z = 5,
  D3DCUBEMAP_FACE_FORCE_DWORD = 0xffffffff
} D3DCUBEMAP_FACES;

typedef struct _D3DVOLUME_DESC {
  D3DFORMAT Format;
  D3DRESOURCETYPE Type;
  DWORD Usage;
  D3DPOOL Pool;
  UINT Width;
  UINT Height;
  UINT Depth;
} D3DVOLUME_DESC;

typedef struct _D3DPRESENT_PARAMETERS {
  UINT BackBufferWidth;
  UINT BackBufferHeight;
  D3DFORMAT BackBufferFormat;
  UINT BackBufferCount;
  D3DMULTISAMPLE_TYPE MultiSampleType;
  D3DSWAPEFFECT SwapEffect;
  HWND hDeviceWindow;
  BOOL Windowed;
  BOOL EnableAutoDepthStencil;
  D3DFORMAT AutoDepthStencilFormat;
  DWORD Flags;
  UINT FullScreen_RefreshRateInHz;
  UINT FullScreen_PresentationInterval;
} D3DPRESENT_PARAMETERS;

typedef struct _D3DGAMMARAMP {
  WORD red[256];
  WORD green[256];
  WORD blue[256];
} D3DGAMMARAMP;

#define D3DSGR_NO_CALIBRATION 0x00000000
#define D3DSGR_CALIBRATE 0x00000001

#define D3DCREATE_FPU_PRESERVE 0x00000002
#define D3DCREATE_HARDWARE_VERTEXPROCESSING 0x00000040
#define D3DCREATE_SOFTWARE_VERTEXPROCESSING 0x00000020
#define D3DCREATE_MIXED_VERTEXPROCESSING 0x00000080

#define D3DLOCK_READONLY 0x00000010L
#define D3DLOCK_DISCARD 0x00002000L
#define D3DLOCK_NOOVERWRITE 0x00001000L
#define D3DLOCK_NOSYSLOCK 0x00000800L
#define D3DLOCK_NO_DIRTY_UPDATE 0x00000001L

#define D3D_SDK_VERSION 220

#define D3DPRESENT_INTERVAL_DEFAULT 0x00000000
#define D3DPRESENT_INTERVAL_ONE 0x00000001
#define D3DPRESENT_INTERVAL_TWO 0x00000002
#define D3DPRESENT_INTERVAL_THREE 0x00000004
#define D3DPRESENT_INTERVAL_FOUR 0x00000008
#define D3DPRESENT_INTERVAL_IMMEDIATE 0x80000000
#define D3DPRESENT_RATE_DEFAULT 0

#define D3DUSAGE_RENDERTARGET 0x00000001L
#define D3DUSAGE_DEPTHSTENCIL 0x00000002L
#define D3DUSAGE_DYNAMIC 0x00000200L
#define D3DUSAGE_WRITEONLY 0x00000008L
#define D3DUSAGE_SOFTWAREPROCESSING 0x00000010L
#define D3DUSAGE_DONOTCLIP 0x00000020L
#define D3DUSAGE_POINTS 0x00000040L
#define D3DUSAGE_RTPATCHES 0x00000080L
#define D3DUSAGE_NPATCHES 0x00000100L

#define D3DADAPTER_DEFAULT 0
#define D3DCLEAR_TARGET 0x00000001
#define D3DCLEAR_ZBUFFER 0x00000002
#define D3DCLEAR_STENCIL 0x00000004

typedef enum _D3DPRIMITIVETYPE {
  D3DPT_POINTLIST = 1,
  D3DPT_LINELIST = 2,
  D3DPT_LINESTRIP = 3,
  D3DPT_TRIANGLELIST = 4,
  D3DPT_TRIANGLESTRIP = 5,
  D3DPT_TRIANGLEFAN = 6,
  D3DPT_FORCE_DWORD = 0x7fffffff
} D3DPRIMITIVETYPE;

#define D3DERR_CONFLICTINGTEXTUREFILTER ((HRESULT)0x8876087EL)
#define D3DERR_CONFLICTINGTEXTUREPALETTE ((HRESULT)0x8876087FL)
#define D3DERR_DEVICELOST ((HRESULT)0x88760868L)
#define D3DERR_DEVICENOTRESET ((HRESULT)0x88760869L)
#define D3DERR_NOTFOUND ((HRESULT)0x88760866L)
#define D3DERR_MOREDATA ((HRESULT)0x88760867L)
#define D3DERR_DRIVERINTERNALERROR ((HRESULT)0x8876086cL)

#define D3D_OK 0L
#define D3DERR_OUTOFVIDEOMEMORY ((HRESULT)0x88760864L)
#define D3DERR_NOTAVAILABLE ((HRESULT)0x8876086aL)
#define D3DERR_TOOMANYOPERATIONS ((HRESULT)0x88760871L)

#define D3DPRASTERCAPS_FOGRANGE 0x00010000
#define D3DFOG_NONE 0
#define D3DFOG_EXP 1
#define D3DFOG_EXP2 2
#define D3DFOG_LINEAR 3
#define D3DMCS_MATERIAL 0
#define D3DMCS_COLOR1 1
#define D3DMCS_COLOR2 2
#define D3DERR_UNSUPPORTEDALPHAARG ((HRESULT)0x88760872L)
#define D3DERR_UNSUPPORTEDALPHAOPERATION ((HRESULT)0x88760873L)
#define D3DERR_UNSUPPORTEDCOLORARG ((HRESULT)0x88760874L)
#define D3DERR_UNSUPPORTEDCOLOROPERATION ((HRESULT)0x88760875L)
#define D3DERR_UNSUPPORTEDFACTORVALUE ((HRESULT)0x88760876L)
#define D3DERR_UNSUPPORTEDTEXTUREFILTER ((HRESULT)0x88760877L)
#define D3DERR_WRONGTEXTUREFORMAT ((HRESULT)0x88760878L)

typedef enum _D3DBACKBUFFER_TYPE {
  D3DBACKBUFFER_TYPE_MONO = 0,
  D3DBACKBUFFER_TYPE_LEFT = 1,
  D3DBACKBUFFER_TYPE_RIGHT = 2,
  D3DBACKBUFFER_TYPE_FORCE_DWORD = 0x7fffffff
} D3DBACKBUFFER_TYPE;

typedef struct _D3DDISPLAYMODE {
  UINT Width;
  UINT Height;
  UINT RefreshRate;
  D3DFORMAT Format;
} D3DDISPLAYMODE;

typedef struct _D3DINDEXBUFFER_DESC {
  D3DFORMAT Format;
  D3DRESOURCETYPE Type;
  DWORD Usage;
  D3DPOOL Pool;
  UINT Size;
} D3DINDEXBUFFER_DESC;

typedef struct _D3DVERTEXBUFFER_DESC {
  D3DFORMAT Format;
  D3DRESOURCETYPE Type;
  DWORD Usage;
  D3DPOOL Pool;
  UINT Size;
  DWORD FVF;
} D3DVERTEXBUFFER_DESC;

#define D3DFVF_RESERVED0 0x001
#define D3DFVF_XYZ 0x002
#define D3DFVF_XYZRHW 0x004
#define D3DFVF_XYZB1 0x006
#define D3DFVF_XYZB2 0x008
#define D3DFVF_XYZB3 0x00a
#define D3DFVF_XYZB4 0x00c
#define D3DFVF_XYZB5 0x00e
#define D3DFVF_NORMAL 0x010
#define D3DFVF_PSIZE 0x020
#define D3DFVF_DIFFUSE 0x040
#define D3DFVF_SPECULAR 0x080
#define D3DFVF_TEX0 0x000
#define D3DFVF_TEX1 0x100
#define D3DFVF_TEX2 0x200
#define D3DFVF_TEX3 0x300
#define D3DFVF_TEX4 0x400
#define D3DFVF_TEX5 0x500
#define D3DFVF_TEX6 0x600
#define D3DFVF_TEX7 0x700
#define D3DFVF_TEX8 0x800

#define D3DFVF_TEXCOUNT_MASK 0x00000F00
#define D3DFVF_TEXCOUNT_SHIFT 8

#define D3DFVF_TEXTUREFORMAT2 0x0
#define D3DFVF_TEXTUREFORMAT1 0x3
#define D3DFVF_TEXTUREFORMAT3 0x1
#define D3DFVF_TEXTUREFORMAT4 0x2

#define D3DFVF_TEXCOORDSIZE3(Index) (D3DFVF_TEXTUREFORMAT3 << (Index * 2 + 16))
#define D3DFVF_TEXCOORDSIZE2(Index) (D3DFVF_TEXTUREFORMAT2 << (Index * 2 + 16))
#define D3DFVF_TEXCOORDSIZE4(Index) (D3DFVF_TEXTUREFORMAT4 << (Index * 2 + 16))
#define D3DFVF_TEXCOORDSIZE1(Index) (D3DFVF_TEXTUREFORMAT1 << (Index * 2 + 16))

// Shader declaration macros
#define D3DVSD_END() 0xFFFFFFFF
#define D3DVSD_STREAM(s) (0x80000000 | (s))
#define D3DVSD_REG(r, t) ((r) | ((t) << 16))

typedef enum _D3DVSDT_TYPE {
  D3DVSDT_FLOAT1 = 0,
  D3DVSDT_FLOAT2 = 1,
  D3DVSDT_FLOAT3 = 2,
  D3DVSDT_FLOAT4 = 3,
  D3DVSDT_D3DCOLOR = 4,
  D3DVSDT_UBYTE4 = 5,
  D3DVSDT_SHORT2 = 6,
  D3DVSDT_SHORT4 = 7,
} D3DVSDT_TYPE;

#define D3DFMT_INDEX16 (D3DFORMAT)101
#define D3DFMT_INDEX32 (D3DFORMAT)102

typedef struct _D3DSURFACE_DESC {
  D3DFORMAT Format;
  D3DRESOURCETYPE Type;
  DWORD Usage;
  D3DPOOL Pool;
  UINT Size;
  D3DMULTISAMPLE_TYPE MultiSampleType;
  UINT Width;
  UINT Height;
} D3DSURFACE_DESC;

typedef struct _D3DRECT {
  long x1;
  long y1;
  long x2;
  long y2;
} D3DRECT;

typedef struct _D3DMATRIX {
  union {
    struct {
      float _11, _12, _13, _14;
      float _21, _22, _23, _24;
      float _31, _32, _33, _34;
      float _41, _42, _43, _44;
    };
    float m[4][4];
  };
} D3DMATRIX;

typedef struct _D3DVECTOR {
  float x;
  float y;
  float z;
} D3DVECTOR;

typedef struct _D3DLOCKED_RECT {
  INT Pitch;
  void *pBits;
} D3DLOCKED_RECT;

typedef struct _D3DLOCKED_BOX {
  int RowPitch;
  int SlicePitch;
  void *pBits;
} D3DLOCKED_BOX;

typedef enum _D3DRENDERSTATETYPE {
  D3DRS_ZENABLE = 7,
  D3DRS_FILLMODE = 8,
  D3DRS_SHADEMODE = 9,
  D3DRS_ZWRITEENABLE = 14,
  D3DRS_ALPHATESTENABLE = 15,
  D3DRS_LASTPIXEL = 16,
  D3DRS_SRCBLEND = 19,
  D3DRS_DESTBLEND = 20,
  D3DRS_CULLMODE = 22,
  D3DRS_ZFUNC = 23,
  D3DRS_ALPHAREF = 24,
  D3DRS_ALPHAFUNC = 25,
  D3DRS_DITHERENABLE = 26,
  D3DRS_ALPHABLENDENABLE = 27,
  D3DRS_FOGENABLE = 28,
  D3DRS_SPECULARENABLE = 29,
  D3DRS_FOGCOLOR = 34,
  D3DRS_FOGTABLEMODE = 35,
  D3DRS_FOGSTART = 36,
  D3DRS_FOGEND = 37,
  D3DRS_FOGDENSITY = 38,
  D3DRS_EDGEANTIALIAS = 40,
  D3DRS_ZBIAS = 47,
  D3DRS_RANGEFOGENABLE = 48,
  D3DRS_STENCILENABLE = 52,
  D3DRS_STENCILFAIL = 53,
  D3DRS_STENCILZFAIL = 54,
  D3DRS_STENCILPASS = 55,
  D3DRS_STENCILFUNC = 56,
  D3DRS_STENCILREF = 57,
  D3DRS_STENCILMASK = 58,
  D3DRS_STENCILWRITEMASK = 59,
  D3DRS_TEXTUREFACTOR = 60,
  D3DRS_WRAP0 = 128,
  D3DRS_WRAP1 = 129,
  D3DRS_WRAP2 = 130,
  D3DRS_WRAP3 = 131,
  D3DRS_WRAP4 = 132,
  D3DRS_WRAP5 = 133,
  D3DRS_WRAP6 = 134,
  D3DRS_WRAP7 = 135,
  D3DRS_CLIPPING = 136,
  D3DRS_LIGHTING = 137,
  D3DRS_AMBIENT = 139,
  D3DRS_FOGVERTEXMODE = 140,
  D3DRS_COLORVERTEX = 141,
  D3DRS_LOCALVIEWER = 142,
  D3DRS_NORMALIZENORMALS = 143,
  D3DRS_DIFFUSEMATERIALSOURCE = 145,
  D3DRS_SPECULARMATERIALSOURCE = 146,
  D3DRS_AMBIENTMATERIALSOURCE = 147,
  D3DRS_EMISSIVEMATERIALSOURCE = 148,
  D3DRS_VERTEXBLEND = 151,
  D3DRS_CLIPPLANEENABLE = 152,
  D3DRS_SOFTWAREVERTEXPROCESSING = 153,
  D3DRS_POINTSIZE = 154,
  D3DRS_POINTSIZE_MIN = 155,
  D3DRS_POINTSPRITEENABLE = 156,
  D3DRS_POINTSCALEENABLE = 157,
  D3DRS_POINTSCALE_A = 158,
  D3DRS_POINTSCALE_B = 159,
  D3DRS_POINTSCALE_C = 160,
  D3DRS_LINEPATTERN = 10,
  D3DRS_ZVISIBLE = 30,
  D3DRS_MULTISAMPLEANTIALIAS = 161,
  D3DRS_MULTISAMPLEMASK = 162,
  D3DRS_PATCHEDGESTYLE = 163,
  D3DRS_PATCHSEGMENTS = 164,
  D3DRS_DEBUGMONITORTOKEN = 165,
  D3DRS_POINTSIZE_MAX = 166,
  D3DRS_INDEXEDVERTEXBLENDENABLE = 167,
  D3DRS_COLORWRITEENABLE = 168,
  D3DRS_TWEENFACTOR = 170,
  D3DRS_BLENDOP = 171,
  D3DRS_POSITIONORDER = 172,
  D3DRS_NORMALORDER = 173,
  D3DRS_FORCE_DWORD = 0x7fffffff
} D3DRENDERSTATETYPE;

typedef enum _D3DORDER {
  D3DORDER_LINEAR = 1,
  D3DORDER_CUBIC = 2,
  D3DORDER_FORCE_DWORD = 0x7fffffff
} D3DORDER;

typedef enum _D3DVERTEXBLENDFLAGS {
  D3DVBF_DISABLE = 0,
  D3DVBF_1WEIGHTS = 1,
  D3DVBF_2WEIGHTS = 2,
  D3DVBF_3WEIGHTS = 3,
  D3DVBF_TWEENING = 255,
  D3DVBF_0WEIGHTS = 256,
  D3DVBF_FORCE_DWORD = 0x7fffffff
} D3DVERTEXBLENDFLAGS;

typedef uint32_t D3DCOLOR;

typedef struct _D3DCAPS8 {
  DWORD DeviceType;
  UINT AdapterOrdinal;
  DWORD Caps;
  DWORD Caps2;
  DWORD Caps3;
  DWORD PresentationIntervals;
  DWORD CursorCaps;
  DWORD DevCaps;
  DWORD PrimitiveMiscCaps;
  DWORD RasterCaps;
  DWORD ZCmpCaps;
  DWORD SrcBlendCaps;
  DWORD DestBlendCaps;
  DWORD AlphaCmpCaps;
  DWORD ShadeCaps;
  DWORD TextureCaps;
  DWORD TextureFilterCaps;
  DWORD CubeTextureFilterCaps;
  DWORD VolumeTextureFilterCaps;
  DWORD TextureAddressCaps;
  DWORD VolumeTextureAddressCaps;
  DWORD LineCaps;
  DWORD MaxTextureWidth, MaxTextureHeight;
  DWORD MaxVolumeExtent;
  DWORD MaxTextureRepeat;
  DWORD MaxTextureAspectRatio;
  DWORD MaxAnisotropy;
  float MaxVertexW;
  float GuardBandLeft;
  float GuardBandTop;
  float GuardBandRight;
  float GuardBandBottom;
  float ExtentsAdjust;
  DWORD StencilCaps;
  DWORD FVFCaps;
  DWORD TextureOpCaps;
  DWORD MaxTextureBlendStages;
  DWORD MaxSimultaneousTextures;
  DWORD VertexProcessingCaps;
  DWORD MaxActiveLights;
  DWORD MaxUserClipPlanes;
  DWORD MaxVertexBlendMatrices;
  DWORD MaxVertexBlendMatrixIndex;
  float MaxPointSize;
  DWORD MaxPrimitiveCount;
  DWORD MaxVertexIndex;
  DWORD MaxStreams;
  DWORD MaxStreamStride;
  DWORD VertexShaderVersion;
  DWORD MaxVertexShaderConst;
  DWORD PixelShaderVersion;
  float MaxPixelShaderValue;
} D3DCAPS8;

#define D3DPMISCCAPS_COLORWRITEENABLE 0x00000080L

#define D3DTEXOPCAPS_DISABLE 0x00000001
#define D3DTEXOPCAPS_SELECTARG1 0x00000002
#define D3DTEXOPCAPS_SELECTARG2 0x00000004
#define D3DTEXOPCAPS_MODULATE 0x00000008
#define D3DTEXOPCAPS_MODULATE2X 0x00000010
#define D3DTEXOPCAPS_MODULATE4X 0x00000020
#define D3DTEXOPCAPS_ADD 0x00000040
#define D3DTEXOPCAPS_ADDSIGNED 0x00000080
#define D3DTEXOPCAPS_ADDSIGNED2X 0x00000100
#define D3DTEXOPCAPS_SUBTRACT 0x00000200
#define D3DTEXOPCAPS_ADDSMOOTH 0x00000400
#define D3DTEXOPCAPS_BLENDDIFFUSEALPHA 0x00000800
#define D3DTEXOPCAPS_BLENDTEXTUREALPHA 0x00001000
#define D3DTEXOPCAPS_BLENDFACTORALPHA 0x00002000
#define D3DTEXOPCAPS_BLENDTEXTUREALPHAPM 0x00004000
#define D3DTEXOPCAPS_BLENDCURRENTALPHA 0x00008000
#define D3DTEXOPCAPS_PREMODULATE 0x00010000
#define D3DTEXOPCAPS_MODULATEALPHA_ADDCOLOR 0x00020000
#define D3DTEXOPCAPS_MODULATECOLOR_ADDALPHA 0x00040000
#define D3DTEXOPCAPS_MODULATEINVALPHA_ADDCOLOR 0x00080000
#define D3DTEXOPCAPS_MODULATEINVCOLOR_ADDALPHA 0x00100000
#define D3DTEXOPCAPS_BUMPENVMAP 0x00200000
#define D3DTEXOPCAPS_BUMPENVMAPLUMINANCE 0x00400000
#define D3DTEXOPCAPS_DOTPRODUCT3 0x00800000
#define D3DTEXOPCAPS_MULTIPLYADD 0x01000000
#define D3DTEXOPCAPS_LERP 0x02000000

typedef struct _D3DCOLORVALUE {
  float r;
  float g;
  float b;
  float a;
} D3DCOLORVALUE;

typedef struct _D3DMATERIAL8 {
  D3DCOLORVALUE Diffuse;
  D3DCOLORVALUE Ambient;
  D3DCOLORVALUE Specular;
  D3DCOLORVALUE Emissive;
  float Power;
} D3DMATERIAL8;

typedef enum _D3DLIGHTTYPE {
  D3DLIGHT_POINT = 1,
  D3DLIGHT_SPOT = 2,
  D3DLIGHT_DIRECTIONAL = 3,
  D3DLIGHT_FORCE_DWORD = 0x7fffffff
} D3DLIGHTTYPE;

typedef struct _D3DLIGHT8 {
  D3DLIGHTTYPE Type;
  D3DCOLORVALUE Diffuse;
  D3DCOLORVALUE Ambient;
  D3DCOLORVALUE Specular;
  D3DVECTOR Position;
  D3DVECTOR Direction;
  float Range;
  float Falloff;
  float Attenuation0;
  float Attenuation1;
  float Attenuation2;
  float Theta;
  float Phi;
} D3DLIGHT8;

typedef struct _D3DVIEWPORT8 {
  DWORD X;
  DWORD Y;
  DWORD Width;
  DWORD Height;
  float MinZ;
  float MaxZ;
} D3DVIEWPORT8;

typedef enum _D3DTRANSFORMSTATETYPE {
  D3DTS_VIEW = 2,
  D3DTS_PROJECTION = 3,
  D3DTS_TEXTURE0 = 16,
  D3DTS_TEXTURE1 = 17,
  D3DTS_TEXTURE2 = 18,
  D3DTS_TEXTURE3 = 19,
  D3DTS_TEXTURE4 = 20,
  D3DTS_TEXTURE5 = 21,
  D3DTS_TEXTURE6 = 22,
  D3DTS_TEXTURE7 = 23,
  D3DTS_WORLD = 256,
} D3DTRANSFORMSTATETYPE;

typedef enum _D3DFILLMODE {
  D3DFILL_POINT = 1,
  D3DFILL_WIREFRAME = 2,
  D3DFILL_SOLID = 3,
} D3DFILLMODE;

typedef enum _D3DSHADEMODE {
  D3DSHADE_FLAT = 1,
  D3DSHADE_GOURAUD = 2,
  D3DSHADE_PHONG = 3,
} D3DSHADEMODE;

typedef enum _D3DBLEND {
  D3DBLEND_ZERO = 1,
  D3DBLEND_ONE = 2,
  D3DBLEND_SRCCOLOR = 3,
  D3DBLEND_INVSRCCOLOR = 4,
  D3DBLEND_SRCALPHA = 5,
  D3DBLEND_INVSRCALPHA = 6,
  D3DBLEND_DESTALPHA = 7,
  D3DBLEND_INVDESTALPHA = 8,
  D3DBLEND_DESTCOLOR = 9,
  D3DBLEND_INVDESTCOLOR = 10,
  D3DBLEND_SRCALPHASAT = 11,
  D3DBLEND_BOTHSRCALPHA = 12,
  D3DBLEND_BOTHINVSRCALPHA = 13,
} D3DBLEND;

typedef enum _D3DCULL {
  D3DCULL_NONE = 1,
  D3DCULL_CW = 2,
  D3DCULL_CCW = 3,
} D3DCULL;

typedef enum _D3DTEXTURESTAGESTATETYPE {
  D3DTSS_COLOROP = 1,
  D3DTSS_COLORARG1 = 2,
  D3DTSS_COLORARG2 = 3,
  D3DTSS_ALPHAOP = 4,
  D3DTSS_ALPHAARG1 = 5,
  D3DTSS_ALPHAARG2 = 6,
  D3DTSS_BUMPENVMAT00 = 7,
  D3DTSS_BUMPENVMAT01 = 8,
  D3DTSS_BUMPENVMAT10 = 9,
  D3DTSS_BUMPENVMAT11 = 10,
  D3DTSS_TEXCOORDINDEX = 11,
  D3DTSS_ADDRESSU = 13,
  D3DTSS_ADDRESSV = 14,
  D3DTSS_BORDERCOLOR = 15,
  D3DTSS_MAGFILTER = 16,
  D3DTSS_MINFILTER = 17,
  D3DTSS_MIPFILTER = 18,
  D3DTSS_MIPMAPLODBIAS = 19,
  D3DTSS_MAXMIPLEVEL = 20,
  D3DTSS_MAXANISOTROPY = 21,
  D3DTSS_BUMPENVLSCALE = 22,
  D3DTSS_BUMPENVLOFFSET = 23,
  D3DTSS_TEXTURETRANSFORMFLAGS = 24,
  D3DTSS_ADDRESSW = 25,
  D3DTSS_COLORARG0 = 26,
  D3DTSS_ALPHAARG0 = 27,
  D3DTSS_RESULTARG = 28,
} D3DTEXTURESTAGESTATETYPE;

#define D3DDEVCAPS_HWTRANSFORMANDLIGHT 0x00010000L
#define D3DDEVCAPS_NPATCHES 0x01000000L
#define D3DCAPS2_FULLSCREENGAMMA 0x00020000L
#define D3DPRASTERCAPS_ZBIAS 0x00004000L

#define D3DTEXOPCAPS_MODULATEALPHA_ADDCOLOR 0x00008000L
#define D3DTEXOPCAPS_DOTPRODUCT3 0x00010000L
#define D3DTEXOPCAPS_BUMPENVMAP 0x00020000L
#define D3DTEXOPCAPS_BUMPENVMAPLUMINANCE 0x00040000L

#define D3DPTEXTURECAPS_CUBEMAP 0x00000400L
#define D3DPTFILTERCAPS_MINFPOINT 0x00000100L
#define D3DPTFILTERCAPS_MINFLINEAR 0x00000200L
#define D3DPTFILTERCAPS_MINFANISOTROPIC 0x00000400L
#define D3DPTFILTERCAPS_MIPFPOINT 0x00010000L
#define D3DPTFILTERCAPS_MIPFLINEAR 0x00020000L
#define D3DPTFILTERCAPS_MAGFPOINT 0x01000000L
#define D3DPTFILTERCAPS_MAGFLINEAR 0x02000000L
#define D3DPTFILTERCAPS_MAGFANISOTROPIC 0x04000000L

#define D3DFVF_LASTBETA_UBYTE4 0x1000

#define D3DDP_MAXTEXCOORD 8

typedef enum _D3DCMPFUNC {
  D3DCMP_NEVER = 1,
  D3DCMP_LESS = 2,
  D3DCMP_EQUAL = 3,
  D3DCMP_LESSEQUAL = 4,
  D3DCMP_GREATER = 5,
  D3DCMP_NOTEQUAL = 6,
  D3DCMP_GREATEREQUAL = 7,
  D3DCMP_ALWAYS = 8,
  D3DCMP_FORCE_DWORD = 0x7fffffff
} D3DCMPFUNC;

typedef enum _D3DSTENCILOP {
  D3DSTENCILOP_KEEP = 1,
  D3DSTENCILOP_ZERO = 2,
  D3DSTENCILOP_REPLACE = 3,
  D3DSTENCILOP_INCRSAT = 4,
  D3DSTENCILOP_DECRSAT = 5,
  D3DSTENCILOP_INVERT = 6,
  D3DSTENCILOP_INCR = 7,
  D3DSTENCILOP_DECR = 8,
  D3DSTENCILOP_FORCE_DWORD = 0x7fffffff
} D3DSTENCILOP;

typedef enum _D3DBLENDOP {
  D3DBLENDOP_ADD = 1,
  D3DBLENDOP_SUBTRACT = 2,
  D3DBLENDOP_REVSUBTRACT = 3,
  D3DBLENDOP_MIN = 4,
  D3DBLENDOP_MAX = 5,
  D3DBLENDOP_FORCE_DWORD = 0x7fffffff
} D3DBLENDOP;

typedef enum _D3DTEXTUREOP {
  D3DTOP_DISABLE = 1,
  D3DTOP_SELECTARG1 = 2,
  D3DTOP_SELECTARG2 = 3,
  D3DTOP_MODULATE = 4,
  D3DTOP_MODULATE2X = 5,
  D3DTOP_MODULATE4X = 6,
  D3DTOP_ADD = 7,
  D3DTOP_ADDSIGNED = 8,
  D3DTOP_ADDSIGNED2X = 9,
  D3DTOP_SUBTRACT = 10,
  D3DTOP_ADDSMOOTH = 11,
  D3DTOP_BLENDDIFFUSEALPHA = 12,
  D3DTOP_BLENDTEXTUREALPHA = 13,
  D3DTOP_BLENDFACTORALPHA = 14,
  D3DTOP_BLENDTEXTUREALPHAPM = 15,
  D3DTOP_BLENDCURRENTALPHA = 16,
  D3DTOP_PREMODULATE = 17,
  D3DTOP_MODULATEALPHA_ADDCOLOR = 18,
  D3DTOP_MODULATECOLOR_ADDALPHA = 19,
  D3DTOP_MODULATEINVALPHA_ADDCOLOR = 20,
  D3DTOP_MODULATEINVCOLOR_ADDALPHA = 21,
  D3DTOP_BUMPENVMAP = 22,
  D3DTOP_BUMPENVMAPLUMINANCE = 23,
  D3DTOP_DOTPRODUCT3 = 24,
  D3DTOP_MULTIPLYADD = 25,
  D3DTOP_LERP = 26,
  D3DTOP_FORCE_DWORD = 0x7fffffff
} D3DTEXTUREOP;

typedef enum _D3DTEXTURETRANSFORMFLAGS {
  D3DTTFF_DISABLE = 0,
  D3DTTFF_COUNT1 = 1,
  D3DTTFF_COUNT2 = 2,
  D3DTTFF_COUNT3 = 3,
  D3DTTFF_COUNT4 = 4,
  D3DTTFF_PROJECTED = 256,
  D3DTTFF_FORCE_DWORD = 0x7fffffff
} D3DTEXTURETRANSFORMFLAGS;

typedef enum _D3DZBUFFERTYPE {
  D3DZB_FALSE = 0,
  D3DZB_TRUE = 1,
  D3DZB_USEW = 2,
  D3DZB_FORCE_DWORD = 0x7fffffff
} D3DZBUFFERTYPE;

#define D3DTA_DIFFUSE 0x00000000
#define D3DTA_CURRENT 0x00000001
#define D3DTA_TEXTURE 0x00000002
#define D3DTA_TFACTOR 0x00000003
#define D3DTA_SPECULAR 0x00000004
#define D3DTA_TEMP 0x00000005
#define D3DTA_COMPLEMENT 0x00000010
#define D3DTA_ALPHAREPLICATE 0x00000020
#define D3DTA_SELECTMASK 0x0000000f

typedef enum _D3DTEXTUREADDRESS {
  D3DTADDRESS_WRAP = 1,
  D3DTADDRESS_MIRROR = 2,
  D3DTADDRESS_CLAMP = 3,
  D3DTADDRESS_BORDER = 4,
  D3DTADDRESS_MIRRORONCE = 5,
  D3DTADDRESS_FORCE_DWORD = 0x7fffffff
} D3DTEXTUREADDRESS;

typedef enum _D3DTEXTUREFILTERTYPE {
  D3DTEXF_NONE = 0,
  D3DTEXF_POINT = 1,
  D3DTEXF_LINEAR = 2,
  D3DTEXF_ANISOTROPIC = 3,
  D3DTEXF_FLATCUBIC = 4,
  D3DTEXF_GAUSSIANCUBIC = 5,
  D3DTEXF_FORCE_DWORD = 0x7fffffff
} D3DTEXTUREFILTERTYPE;

#define D3DWRAP_U 0x00000001
#define D3DWRAP_V 0x00000002
#define D3DWRAP_W 0x00000004

#define D3DCOLORWRITEENABLE_RED (1L << 0)
#define D3DCOLORWRITEENABLE_GREEN (1L << 1)
#define D3DCOLORWRITEENABLE_BLUE (1L << 2)
#define D3DCOLORWRITEENABLE_ALPHA (1L << 3)

#define D3DTSS_TCI_PASSTHRU 0x00000000
#define D3DTSS_TCI_CAMERASPACEPOSITION 0x00010000
#define D3DTSS_TCI_CAMERASPACENORMAL 0x00020000
#define D3DTSS_TCI_CAMERASPACEREFLECTIONVECTOR 0x00030000

typedef enum _D3DPATCHEDGESTYLE {
  D3DPATCHEDGE_DISCRETE = 0,
  D3DPATCHEDGE_CONTINUOUS = 1,
  D3DPATCHEDGE_FORCE_DWORD = 0x7fffffff
} D3DPATCHEDGESTYLE;

typedef enum _D3DDEBUGMONITORTOKENS {
  D3DDMT_ENABLE = 0,
  D3DDMT_DISABLE = 1,
  D3DDMT_FORCE_DWORD = 0x7fffffff
} D3DDEBUGMONITORTOKENS;

struct IDirect3DResource8 : public IUnknown {
  STDMETHOD(GetDevice)(THIS_ IDirect3DDevice8 **ppDevice) PURE;
  STDMETHOD(SetPrivateData)(THIS_ REFGUID refguid, CONST void *pData,
                            DWORD SizeOfData, DWORD Flags) PURE;
  STDMETHOD(GetPrivateData)(THIS_ REFGUID refguid, void *pData,
                            DWORD *pSizeOfData) PURE;
  STDMETHOD(FreePrivateData)(THIS_ REFGUID refguid) PURE;
  STDMETHOD_(DWORD, SetPriority)(THIS_ DWORD PriorityNew) PURE;
  STDMETHOD_(DWORD, GetPriority)(THIS) PURE;
  STDMETHOD_(void, PreLoad)(THIS) PURE;
  STDMETHOD_(D3DRESOURCETYPE, GetType)(THIS) PURE;
};

struct IDirect3DVertexBuffer8 : public IDirect3DResource8 {
  STDMETHOD(Lock)(THIS_ UINT OffsetToLock, UINT SizeToLock, BYTE **ppbData,
                  DWORD Flags) PURE;
  STDMETHOD(Unlock)(THIS) PURE;
  STDMETHOD(GetDesc)(THIS_ D3DVERTEXBUFFER_DESC *pDesc) PURE;
};

struct IDirect3DIndexBuffer8 : public IDirect3DResource8 {
  STDMETHOD(Lock)(THIS_ UINT OffsetToLock, UINT SizeToLock, BYTE **ppbData,
                  DWORD Flags) PURE;
  STDMETHOD(Unlock)(THIS) PURE;
  STDMETHOD(GetDesc)(THIS_ D3DINDEXBUFFER_DESC *pDesc) PURE;
};

struct IDirect3DSurface8 : public IUnknown {
  STDMETHOD(GetDevice)(THIS_ IDirect3DDevice8 **ppDevice) PURE;
  STDMETHOD(SetPrivateData)(THIS_ REFGUID refguid, CONST void *pData,
                            DWORD SizeOfData, DWORD Flags) PURE;
  STDMETHOD(GetPrivateData)(THIS_ REFGUID refguid, void *pData,
                            DWORD *pSizeOfData) PURE;
  STDMETHOD(FreePrivateData)(THIS_ REFGUID refguid) PURE;
  STDMETHOD(GetContainer)(THIS_ REFIID riid, void **ppContainer) PURE;
  STDMETHOD(GetDesc)(THIS_ D3DSURFACE_DESC *pDesc) PURE;
  STDMETHOD(LockRect)(THIS_ D3DLOCKED_RECT *pLockedRect, CONST RECT *pRect,
                      DWORD Flags) PURE;
  STDMETHOD(UnlockRect)(THIS) PURE;
};

struct IDirect3DBaseTexture8 : public IDirect3DResource8 {
  STDMETHOD_(DWORD, SetLOD)(THIS_ DWORD LODNew) PURE;
  STDMETHOD_(DWORD, GetLOD)(THIS) PURE;
  STDMETHOD_(DWORD, GetLevelCount)(THIS) PURE;
};

struct IDirect3DTexture8 : public IDirect3DBaseTexture8 {
  STDMETHOD(GetLevelDesc)(THIS_ UINT Level, D3DSURFACE_DESC *pDesc) PURE;
  STDMETHOD(GetSurfaceLevel)
  (THIS_ UINT Level, IDirect3DSurface8 **ppSurfaceLevel) PURE;
  STDMETHOD(LockRect)
  (THIS_ UINT Level, D3DLOCKED_RECT *pLockedRect, CONST RECT *pRect,
   DWORD Flags) PURE;
  STDMETHOD(UnlockRect)(THIS_ UINT Level) PURE;
  STDMETHOD(AddDirtyRect)(THIS_ CONST RECT *pDirtyRect) PURE;
};

struct IDirect3D8 : public IUnknown {
  STDMETHOD(QueryInterface)(THIS_ REFIID riid, void **ppvObj) PURE;
  STDMETHOD_(ULONG, AddRef)(THIS) PURE;
  STDMETHOD_(ULONG, Release)(THIS) PURE;
  STDMETHOD(RegisterSoftwareDevice)(THIS_ void *pInitializeFunction) PURE;
  STDMETHOD_(UINT, GetAdapterCount)(THIS) PURE;
  STDMETHOD(GetAdapterIdentifier)
  (THIS_ UINT Adapter, DWORD Flags, D3DADAPTER_IDENTIFIER8 *pIdentifier) PURE;
  STDMETHOD_(UINT, GetAdapterModeCount)(THIS_ UINT Adapter) PURE;
  STDMETHOD(EnumAdapterModes)(THIS_ UINT Adapter, UINT Mode,
                              D3DDISPLAYMODE *pMode) PURE;
  STDMETHOD(GetAdapterDisplayMode)(THIS_ UINT Adapter,
                                   D3DDISPLAYMODE *pMode) PURE;
  STDMETHOD(CheckDeviceType)
  (THIS_ UINT Adapter, DWORD CheckType, D3DFORMAT DisplayFormat,
   D3DFORMAT BackBufferFormat, BOOL Windowed) PURE;
  STDMETHOD(CheckDeviceFormat)
  (THIS_ UINT Adapter, DWORD DeviceType, D3DFORMAT AdapterFormat, DWORD Usage,
   DWORD RType, D3DFORMAT CheckFormat) PURE;
  STDMETHOD(CheckDeviceMultiSampleType)
  (THIS_ UINT Adapter, DWORD DeviceType, D3DFORMAT SurfaceFormat, BOOL Windowed,
   DWORD MultiSampleType) PURE;
  STDMETHOD(CheckDepthStencilMatch)
  (THIS_ UINT Adapter, DWORD DeviceType, D3DFORMAT AdapterFormat,
   D3DFORMAT RenderTargetFormat, D3DFORMAT DepthStencilFormat) PURE;
  STDMETHOD(GetDeviceCaps)
  (THIS_ UINT Adapter, DWORD DeviceType, D3DCAPS8 *pCaps) PURE;
  STDMETHOD_(HMONITOR, GetAdapterMonitor)(THIS_ UINT Adapter) PURE;
  STDMETHOD(CreateDevice)
  (THIS_ UINT Adapter, D3DDEVTYPE DeviceType, HWND hFocusWindow,
   DWORD BehaviorFlags, D3DPRESENT_PARAMETERS *pPresentationParameters,
   IDirect3DDevice8 **ppReturnedDeviceInterface) PURE;
};

struct IDirect3DDevice8 : public IUnknown {
  STDMETHOD(QueryInterface)(THIS_ REFIID riid, void **ppvObj) PURE;
  STDMETHOD_(ULONG, AddRef)(THIS) PURE;
  STDMETHOD_(ULONG, Release)(THIS) PURE;
  STDMETHOD(TestCooperativeLevel)(THIS) PURE;
  STDMETHOD(SetVertexShader)(THIS_ DWORD v) PURE;
  STDMETHOD(DeleteVertexShader)(THIS_ DWORD v) PURE;
  STDMETHOD(SetPixelShader)(THIS_ DWORD v) PURE;
  STDMETHOD(DeletePixelShader)(THIS_ DWORD v) PURE;
  STDMETHOD(CreatePixelShader)(THIS_ const DWORD *pFunction,
                               DWORD *pHandle) PURE;
  STDMETHOD(SetVertexShaderConstant)
  (THIS_ DWORD r, const void *d, DWORD c) PURE;
  STDMETHOD(SetPixelShaderConstant)
  (THIS_ DWORD r, const void *d, DWORD c) PURE;
  STDMETHOD(SetTransform)(THIS_ D3DTRANSFORMSTATETYPE t,
                          const D3DMATRIX *m) PURE;
  STDMETHOD(GetTransform)(THIS_ D3DTRANSFORMSTATETYPE t, D3DMATRIX *m) PURE;
  STDMETHOD(LightEnable)(THIS_ DWORD i, BOOL b) PURE;
  STDMETHOD(SetTexture)(THIS_ DWORD s, IDirect3DBaseTexture8 *t) PURE;
  STDMETHOD(SetRenderState)(THIS_ D3DRENDERSTATETYPE s, DWORD v) PURE;
  STDMETHOD(GetRenderState)(THIS_ D3DRENDERSTATETYPE s, DWORD *v) PURE;
  STDMETHOD(SetTextureStageState)
  (THIS_ DWORD s, D3DTEXTURESTAGESTATETYPE t, DWORD v) PURE;
  STDMETHOD(SetLight)(THIS_ DWORD i, const D3DLIGHT8 *l) PURE;
  STDMETHOD(SetViewport)(THIS_ const D3DVIEWPORT8 *v) PURE;
  STDMETHOD(Clear)(THIS_ DWORD c, const void *r, DWORD f, D3DCOLOR cl, float z,
                   DWORD s) PURE;
  STDMETHOD(BeginScene)(THIS) PURE;
  STDMETHOD(EndScene)(THIS) PURE;
  STDMETHOD(Present)(THIS_ const void *s, const void *d, HWND w,
                     const void *r) PURE;
  STDMETHOD(GetBackBuffer)
  (THIS_ UINT i, D3DBACKBUFFER_TYPE t, IDirect3DSurface8 **b) PURE;
  STDMETHOD(GetFrontBuffer)(THIS_ IDirect3DSurface8 *d) PURE;
  STDMETHOD(UpdateTexture)
  (THIS_ IDirect3DBaseTexture8 *s, IDirect3DBaseTexture8 *d) PURE;
  STDMETHOD(SetIndices)(THIS_ IDirect3DIndexBuffer8 *i, UINT b) PURE;
  STDMETHOD(DrawIndexedPrimitive)
  (THIS_ DWORD t, UINT m, UINT v, UINT s, UINT p) PURE;
  STDMETHOD(SetStreamSource)(THIS_ UINT s, IDirect3DVertexBuffer8 *v,
                             UINT d) PURE;
  STDMETHOD(DrawPrimitive)(THIS_ DWORD t, UINT s, UINT p) PURE;
  STDMETHOD(CreateTexture)
  (THIS_ UINT w, UINT h, UINT l, DWORD u, D3DFORMAT f, D3DPOOL p,
   IDirect3DTexture8 **t) PURE;
  STDMETHOD(CreateVolumeTexture)
  (THIS_ UINT w, UINT h, UINT d, UINT l, DWORD u, D3DFORMAT f, D3DPOOL p,
   IDirect3DVolumeTexture8 **t) PURE;
  STDMETHOD(CreateImageSurface)
  (THIS_ UINT w, UINT h, D3DFORMAT f, IDirect3DSurface8 **s) PURE;
  STDMETHOD(CreateCubeTexture)
  (THIS_ UINT s, UINT l, DWORD u, D3DFORMAT f, D3DPOOL p,
   IDirect3DCubeTexture8 **t) PURE;
  STDMETHOD(CreateVertexBuffer)
  (THIS_ UINT l, DWORD u, DWORD f, D3DPOOL p, IDirect3DVertexBuffer8 **v) PURE;
  STDMETHOD(CreateIndexBuffer)
  (THIS_ UINT l, DWORD u, D3DFORMAT f, D3DPOOL p, IDirect3DIndexBuffer8 **i)
      PURE;
  STDMETHOD(GetRenderTarget)(THIS_ IDirect3DSurface8 **s) PURE;
  STDMETHOD(SetRenderTarget)
  (THIS_ IDirect3DSurface8 *s, IDirect3DSurface8 *d) PURE;
  STDMETHOD(GetDepthStencilSurface)(THIS_ IDirect3DSurface8 **s) PURE;
  STDMETHOD(SetDepthStencilSurface)(THIS_ IDirect3DSurface8 *s) PURE;
  STDMETHOD(CopyRects)
  (THIS_ IDirect3DSurface8 *s, const void *r, UINT c, IDirect3DSurface8 *d,
   const void *p) PURE;
  STDMETHOD(Reset)(THIS_ D3DPRESENT_PARAMETERS *p) PURE;
  STDMETHOD(GetDeviceCaps)(THIS_ D3DCAPS8 *c) PURE;
  STDMETHOD(GetAdapterIdentifier)
  (THIS_ UINT a, DWORD f, D3DADAPTER_IDENTIFIER8 *i) PURE;
  STDMETHOD(SetMaterial)(THIS_ const D3DMATERIAL8 *m) PURE;
  STDMETHOD(SetClipPlane)(THIS_ DWORD i, const float *p) PURE;
  STDMETHOD(ResourceManagerDiscardBytes)(THIS_ DWORD Bytes) PURE;
  STDMETHOD(ValidateDevice)(THIS_ DWORD *pPasses) PURE;
  STDMETHOD(GetDisplayMode)(THIS_ D3DDISPLAYMODE *pMode) PURE;
  STDMETHOD(CreateAdditionalSwapChain)
  (THIS_ D3DPRESENT_PARAMETERS *pModel, IDirect3DSwapChain8 **pSwapChain) PURE;
  STDMETHOD_(UINT, GetAvailableTextureMem)(THIS) PURE;
  STDMETHOD(DrawPrimitiveUP)(THIS_ DWORD PrimitiveType, UINT PrimitiveCount,
                             const void *pVertexStreamZeroData,
                             UINT VertexStreamZeroStride) PURE;
  STDMETHOD(DrawIndexedPrimitiveUP)(THIS_ DWORD PrimitiveType,
                                    UINT MinVertexIndex, UINT NumVertexIndices,
                                    UINT PrimitiveCount, const void *pIndexData,
                                    D3DFORMAT IndexDataFormat,
                                    const void *pVertexStreamZeroData,
                                    UINT VertexStreamZeroStride) PURE;
  STDMETHOD(CreateVertexShader)(THIS_ const DWORD *pDeclaration,
                                const DWORD *pFunction, DWORD *pHandle,
                                DWORD Flags) PURE;
  STDMETHOD(SetGammaRamp)(THIS_ DWORD Flags, const D3DGAMMARAMP *pRamp) PURE;
  STDMETHOD(GetGammaRamp)(THIS_ D3DGAMMARAMP *pRamp) PURE;
};

struct IDirect3DVolumeTexture8 : public IDirect3DBaseTexture8 {
  STDMETHOD(QueryInterface)(THIS_ REFIID riid, void **ppvObj) PURE;
  STDMETHOD_(ULONG, AddRef)(THIS) PURE;
  STDMETHOD_(ULONG, Release)(THIS) PURE;
  STDMETHOD(GetLevelDesc)(THIS_ UINT Level, D3DVOLUME_DESC *pDesc) PURE;
  STDMETHOD(LockBox)(THIS_ UINT Level, D3DLOCKED_BOX *pLockedVolume,
                     const void *pBox, DWORD Flags) PURE;
  STDMETHOD(UnlockBox)(THIS_ UINT Level) PURE;
};
struct IDirect3DCubeTexture8 : public IDirect3DBaseTexture8 {
  STDMETHOD(QueryInterface)(THIS_ REFIID riid, void **ppvObj) PURE;
  STDMETHOD_(ULONG, AddRef)(THIS) PURE;
  STDMETHOD_(ULONG, Release)(THIS) PURE;
  STDMETHOD(GetLevelDesc)(THIS_ UINT Level, D3DSURFACE_DESC *pDesc) PURE;
  STDMETHOD(LockRect)(THIS_ D3DCUBEMAP_FACES FaceType, UINT Level,
                      D3DLOCKED_RECT *pLockedRect, const RECT *pRect,
                      DWORD Flags) PURE;
  STDMETHOD(UnlockRect)(THIS_ D3DCUBEMAP_FACES FaceType, UINT Level) PURE;
};
struct IDirect3DVolume8 : public IUnknown {
  STDMETHOD(QueryInterface)(THIS_ REFIID riid, void **ppvObj) PURE;
  STDMETHOD_(ULONG, AddRef)(THIS) PURE;
  STDMETHOD_(ULONG, Release)(THIS) PURE;
};
struct IDirect3DSwapChain8 : public IUnknown {
  STDMETHOD(QueryInterface)(THIS_ REFIID riid, void **ppvObj) PURE;
  STDMETHOD_(ULONG, AddRef)(THIS) PURE;
  STDMETHOD_(ULONG, Release)(THIS) PURE;
  STDMETHOD(Present)
  (THIS_ const void *s, const void *d, HWND w, const void *r) PURE;
  STDMETHOD(GetBackBuffer)
  (THIS_ UINT i, D3DBACKBUFFER_TYPE t, IDirect3DSurface8 **b) PURE;
};

struct ID3DXBuffer : public IUnknown {
  STDMETHOD_(void *, GetBufferPointer)(THIS) PURE;
  STDMETHOD_(DWORD, GetBufferSize)(THIS) PURE;
};
typedef struct ID3DXBuffer *LPD3DXBUFFER;

typedef struct IDirect3D8 *LPDIRECT3D8;
typedef struct IDirect3DDevice8 *LPDIRECT3DDEVICE8;
typedef struct IDirect3DResource8 *LPDIRECT3DRESOURCE8;
typedef struct IDirect3DBaseTexture8 *LPDIRECT3DBASETEXTURE8;
typedef struct IDirect3DTexture8 *LPDIRECT3DTEXTURE8;
typedef struct IDirect3DCubeTexture8 *LPDIRECT3DCUBETEXTURE8;
typedef struct IDirect3DVolumeTexture8 *LPDIRECT3DVOLUMETEXTURE8;
typedef struct IDirect3DSurface8 *LPDIRECT3DSURFACE8;
typedef struct IDirect3DVolume8 *LPDIRECT3DVOLUME8;
typedef struct IDirect3DVertexBuffer8 *LPDIRECT3DVERTEXBUFFER8;
typedef struct IDirect3DIndexBuffer8 *LPDIRECT3DINDEXBUFFER8;
typedef struct IDirect3DSwapChain8 *LPDIRECT3DSWAPCHAIN8;

#ifdef __cplusplus
}
#endif

#endif
