"""Generate the supplementary first-strong-direction table from Unicode 17.0.0.

Input: https://www.unicode.org/Public/17.0.0/ucd/extracted/DerivedBidiClass.txt
Usage: python scripts/generate_supplementary_bidi.py DerivedBidiClass.txt [--check]
"""

import argparse
import hashlib
from pathlib import Path
import re


def generate(source):
    if not source.startswith("# DerivedBidiClass-17.0.0.txt"):
        raise ValueError("Expected Unicode 17.0.0 DerivedBidiClass.txt")
    if hashlib.sha256(source.encode("utf-8")).hexdigest() != "4867b4b7f0731ed1bfcd34cc6251211ff1542541fce0734b6fbda139ee80b3a4":
        raise ValueError("Unexpected Unicode data checksum")
    classes = ["L"] * 0x110000
    aliases = {"Left_To_Right": "L", "Right_To_Left": "R", "Arabic_Letter": "AL"}
    missing = re.findall(r"@missing: ([0-9A-F]+)\.\.([0-9A-F]+); (\w+)", source)
    explicit = re.findall(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)", source, re.M)
    for lo, hi, value in missing + explicit:
        lo, hi = int(lo, 16), int(hi or lo, 16)
        classes[lo:hi + 1] = [aliases.get(value, value)] * (hi - lo + 1)
    directions = ["LeftToRight" if c == "L" else "RightToLeft" if c in ("R", "AL")
                  else "Neutral" for c in classes]
    lines = [
        "// Generated by scripts/generate_supplementary_bidi.py; do not edit.",
        "// Unicode 17.0.0 DerivedBidiClass.txt, including its @missing defaults.",
        "// Copyright 2025 Unicode, Inc. See unicode-license.txt.",
        "// Omitted ranges have direction LeftToRight. Neutral means neither L, R nor AL.",
    ]
    start = 0x10000
    for end in range(start + 1, len(directions) + 1):
        if end == len(directions) or directions[end] != directions[start]:
            if directions[start] != "LeftToRight":
                lines.append("\t{ 0x%05X, 0x%05X, %s }," % (start, end - 1, directions[start]))
            start = end
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = Path(__file__).resolve().parents[1] / "Core/Libraries/Source/WWVegas/WW3D2/supplementarybidi.inl"
    generated = generate(args.source.read_text(encoding="utf-8"))
    if args.check:
        if output.read_text(encoding="utf-8") != generated:
            raise SystemExit("Supplementary bidi table is out of date")
        print("Unicode 17.0.0 supplementary bidi table matches")
    else:
        output.write_text(generated, encoding="utf-8")
