#!/bin/bash

SOURCES=(
  "Core/GameEngine/Source/Common/Audio/AudioEventRTS.cpp"
  "Core/GameEngine/Source/Common/Audio/AudioRequest.cpp"
  "Core/GameEngine/Source/Common/Audio/DynamicAudioEventInfo.cpp"
  "Core/GameEngine/Source/Common/Audio/GameAudio.cpp"
  "Core/GameEngine/Source/Common/Audio/GameMusic.cpp"
  "Core/GameEngine/Source/Common/Audio/GameSounds.cpp"
  "Core/GameEngine/Source/Common/FramePacer.cpp"
  "Core/GameEngine/Source/Common/INI/INI.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/INI.cpp"
  "Core/GameEngine/Source/Common/INI/INIAudioEventInfo.cpp"
  "Core/GameEngine/Source/GameClient/System/Smudge.cpp"
  "Core/GameEngine/Source/GameNetwork/DownloadManager.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpyOverlay.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/MainMenuUtils.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/PeerDefs.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/GSConfig.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/LadderDefs.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/Thread/BuddyThread.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/Thread/PeerThread.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/Thread/PingThread.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/Thread/PersistentStorageThread.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/Thread/GameResultsThread.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/Thread/ThreadUtils.cpp"
  "Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp"
  "Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp"
  "Core/GameEngine/Source/GameNetwork/LANAPICallbacks.cpp"
  "Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DSmudge.cpp"
  "Core/GameEngineDevice/Source/W3DDevice/GameClient/BaseHeightMap.cpp"
  "Core/GameEngineDevice/Source/W3DDevice/GameClient/HeightMap.cpp"
  "Core/GameEngineDevice/Source/W3DDevice/GameClient/FlatHeightMap.cpp"
  "Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DTerrainVisual.cpp"

  "Core/Libraries/Source/WWVegas/WWLib/wwstring.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/mutex.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/shader.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/camera.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/light.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/scene.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/vertmaterial.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/mesh.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hlod.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/animobj.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/boxrobj.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dazzle.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/decalmsh.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/linegrp.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/nullrobj.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/part_buf.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/part_emt.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/part_ldr.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/render2d.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/rinfo.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/ww3dformat.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/proto.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/agg_def.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/collect.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/distlod.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/htree.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/hanim.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/hmdldef.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/ScoreKeeper.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/BodyModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BehaviorModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/UpdateModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/DieModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/UpgradeModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/CaveContain.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/HealContain.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/OpenContain.cpp"
  "Core/GameEngine/Source/Common/RandomValue.cpp"
  "Core/GameEngine/Source/Common/System/ArchiveFile.cpp"
  "Core/GameEngine/Source/Common/System/ArchiveFileSystem.cpp"
  "Core/GameEngine/Source/Common/System/AsciiString.cpp"
  "Core/GameEngine/Source/Common/System/FileSystem.cpp"
  "Core/GameEngine/Source/Common/System/GameType.cpp"
  "Core/GameEngine/Source/Common/System/LocalFile.cpp"
  "Core/GameEngine/Source/Common/System/LocalFileSystem.cpp"
  "Core/GameEngine/Source/Common/System/ObjectStatusTypes.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp"
  "Core/GameEngine/Source/Common/System/RAMFile.cpp"
  "Core/GameEngine/Source/Common/System/Radar.cpp"
  "Core/GameEngine/Source/Common/System/Snapshot.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/System/SaveGame/GameStateMap.cpp"
  "Core/GameEngine/Source/Common/System/StreamingArchiveFile.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/straw.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/xstraw.cpp"
  "Core/GameEngine/Source/Common/System/SubsystemInterface.cpp"
  "Core/GameEngine/Source/Common/System/GameCommon.cpp"
  "Core/GameEngine/Source/Common/System/UnicodeString.cpp"
  "Core/GameEngine/Source/Common/System/Xfer.cpp"
  "Core/GameEngine/Source/Common/System/XferCRC.cpp"
  "Core/GameEngine/Source/Common/System/XferLoad.cpp"
  "Core/GameEngine/Source/Common/System/XferSave.cpp"
  "Core/GameEngine/Source/Common/System/file.cpp"
  "Core/GameEngine/Source/Common/UserPreferences.cpp"
  "Core/GameEngine/Source/Common/System/GameMemory.cpp"
  "Core/GameEngine/Source/Common/System/GameMemoryInit.cpp"
  "Core/GameEngine/Source/GameClient/GUI/ChallengeGenerals.cpp"
  "Core/GameEngine/Source/GameClient/MapUtil.cpp"
  "Core/GameEngine/Source/GameClient/System/ParticleSys.cpp"
  "Core/GameEngine/Source/GameClient/Terrain/TerrainRoads.cpp"
  "Core/GameEngine/Source/GameClient/Terrain/TerrainVisual.cpp"
  "Core/GameEngine/Source/GameClient/View.cpp"
  "Core/GameEngine/Source/GameClient/Snow.cpp"
  "Core/GameEngine/Source/GameClient/Water.cpp"
  "Core/GameEngine/Source/GameClient/VideoPlayer.cpp"
  "Core/GameEngine/Source/GameNetwork/GameInfo.cpp"
  "Core/GameEngine/Source/GameNetwork/FileTransfer.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/Thread/GameResultsThread.cpp"
  "Platform/MacOS/Source/Common/StdBIGFile.cpp"
  "Platform/MacOS/Source/Common/StdBIGFileSystem.cpp"
  "Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp"
  "Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWaterTracks.cpp"
  "Platform/MacOS/Source/Stubs/MacOSW3DShaderManager.mm"
  "Platform/MacOS/Source/Common/StdLocalFile.cpp"
  "Platform/MacOS/Source/Common/StdLocalFileSystem.cpp"
  "Platform/MacOS/Source/Main/StdKeyboard.mm"
  "Platform/MacOS/Source/Main/StdMouse.mm"
  "Core/Libraries/Source/Compression/EAC/huffdecode.cpp"
  "Core/Libraries/Source/Compression/EAC/huffencode.cpp"
  "Core/Libraries/Source/Compression/EAC/refdecode.cpp"
  "Core/Libraries/Source/Compression/EAC/refencode.cpp"
  "Core/Libraries/Source/Compression/CompressionManager.cpp"
  "Core/Libraries/Source/Compression/LZHCompress/NoxCompress.cpp"
  "Core/Libraries/Source/Compression/EAC/btreeabout.cpp"
  "Core/Libraries/Source/Compression/EAC/btreedecode.cpp"
  "Core/Libraries/Source/Compression/EAC/btreeencode.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/dx8texman.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/multilist.cpp"
  "Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp"
  "Core/Libraries/Source/WWVegas/WWDebug/wwmemlog.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp"
  "Dependencies/gamespy/src/chat/chatcallbacks.c"
  "Dependencies/gamespy/src/chat/chatchannel.c"
  "Dependencies/gamespy/src/chat/chatcrypt.c"
  "Dependencies/gamespy/src/chat/chathandlers.c"
  "Dependencies/gamespy/src/chat/chatmain.c"
  "Dependencies/gamespy/src/chat/chatsocket.c"
  "Dependencies/gamespy/src/common/darray.c"
  "Dependencies/gamespy/src/common/gsassert.c"
  "Dependencies/gamespy/src/common/gsavailable.c"
  "Dependencies/gamespy/src/common/gscore.c"
  "Dependencies/gamespy/src/common/gscrypt.c"
  "Dependencies/gamespy/src/common/gsdebug.c"
  "Dependencies/gamespy/src/common/gslargeint.c"
  "Dependencies/gamespy/src/common/gsmemory.c"
  "Dependencies/gamespy/src/common/gsplatform.c"
  "Dependencies/gamespy/src/common/gsplatformsocket.c"
  "Dependencies/gamespy/src/common/gsplatformthread.c"
  "Dependencies/gamespy/src/common/gsplatformutil.c"
  "Dependencies/gamespy/src/common/gsrc4.c"
  "Dependencies/gamespy/src/common/gssha1.c"
  "Dependencies/gamespy/src/common/gsssl.c"
  "Dependencies/gamespy/src/common/gsstringutil.c"
  "Dependencies/gamespy/src/common/gsxml.c"
  "Dependencies/gamespy/src/common/hashtable.c"
#  "Dependencies/gamespy/src/common/macosx/gsthreadmacosx.c"
#  "Dependencies/gamespy/src/common/macosx/gsutilmacosx.c"
  "Dependencies/gamespy/src/common/md5c.c"
#  "Dependencies/gamespy/src/common/nonport.c"
  "Dependencies/gamespy/src/gcdkey/gcdkeyc.c"
  "Dependencies/gamespy/src/gcdkey/gcdkeys.c"
  "Dependencies/gamespy/src/ghttp/ghttpbuffer.c"
  "Dependencies/gamespy/src/ghttp/ghttpcallbacks.c"
  "Dependencies/gamespy/src/ghttp/ghttpcommon.c"
  "Dependencies/gamespy/src/ghttp/ghttpconnection.c"
  "Dependencies/gamespy/src/ghttp/ghttpencryption.c"
  "Dependencies/gamespy/src/ghttp/ghttpmain.c"
  "Dependencies/gamespy/src/ghttp/ghttppost.c"
  "Dependencies/gamespy/src/ghttp/ghttpprocess.c"
  "Dependencies/gamespy/src/ghttp/gssoap.c"
  "Core/Libraries/Source/WWVegas/WWSaveLoad/persistfactory.cpp"
  "Dependencies/gamespy/src/gp/gp.c"
  "Dependencies/gamespy/src/gp/gpi.c"
  "Dependencies/gamespy/src/gp/gpibuddy.c"
  "Dependencies/gamespy/src/gp/gpibuffer.c"
  "Dependencies/gamespy/src/gp/gpicallback.c"
  "Dependencies/gamespy/src/gp/gpiconnect.c"
  "Dependencies/gamespy/src/gp/gpiinfo.c"
  "Dependencies/gamespy/src/gp/gpikeys.c"
  "Dependencies/gamespy/src/gp/gpioperation.c"
  "Dependencies/gamespy/src/gp/gpipeer.c"
  "Dependencies/gamespy/src/gp/gpiprofile.c"
  "Dependencies/gamespy/src/gp/gpisearch.c"
  "Dependencies/gamespy/src/gp/gpitransfer.c"
  "Dependencies/gamespy/src/gp/gpiunique.c"
  "Dependencies/gamespy/src/gp/gpiutility.c"
  "Dependencies/gamespy/src/gt2/gsudpengine.c"
  "Dependencies/gamespy/src/gt2/gt2auth.c"
  "Dependencies/gamespy/src/gt2/gt2buffer.c"
  "Dependencies/gamespy/src/gt2/gt2callback.c"
  "Dependencies/gamespy/src/gt2/gt2connection.c"
  "Dependencies/gamespy/src/gt2/gt2encode.c"
  "Dependencies/gamespy/src/gt2/gt2filter.c"
  "Dependencies/gamespy/src/gt2/gt2main.c"
  "Dependencies/gamespy/src/gt2/gt2message.c"
  "Dependencies/gamespy/src/gt2/gt2socket.c"
  "Dependencies/gamespy/src/gt2/gt2utility.c"
  "Dependencies/gamespy/src/natneg/natify.c"
  "Dependencies/gamespy/src/natneg/natneg.c"
  "Dependencies/gamespy/src/peer/peerautomatch.c"
  "Dependencies/gamespy/src/peer/peercallbacks.c"
  "Dependencies/gamespy/src/peer/peerglobalcallbacks.c"
  "Dependencies/gamespy/src/peer/peerhost.c"
  "Dependencies/gamespy/src/peer/peerkeys.c"
  "Dependencies/gamespy/src/peer/peermain.c"
  "Dependencies/gamespy/src/peer/peermangle.c"
  "Dependencies/gamespy/src/peer/peeroperations.c"
  "Dependencies/gamespy/src/peer/peerping.c"
  "Dependencies/gamespy/src/peer/peerplayers.c"
  "Dependencies/gamespy/src/peer/peerqr.c"
  "Dependencies/gamespy/src/peer/peerrooms.c"
  "Dependencies/gamespy/src/peer/peersb.c"
  "Dependencies/gamespy/src/qr2/qr2.c"
  "Dependencies/gamespy/src/qr2/qr2regkeys.c"
  "Dependencies/gamespy/src/serverbrowsing/sb_crypt.c"
  "Dependencies/gamespy/src/serverbrowsing/sb_queryengine.c"
  "Dependencies/gamespy/src/serverbrowsing/sb_server.c"
  "Dependencies/gamespy/src/serverbrowsing/sb_serverbrowsing.c"
  "Dependencies/gamespy/src/serverbrowsing/sb_serverlist.c"
  "Dependencies/gamespy/src/pinger/pingermain.c"
  "Dependencies/gamespy/src/gstats/gstats.c"
  "Dependencies/gamespy/src/gstats/gbucket.c"
  "Dependencies/gamespy/src/qr/gqueryreporting.c"
  "Core/GameEngine/Source/GameNetwork/GameSpy/StagingRoomGameInfo.cpp"
  "Platform/MacOS/Source/Stubs/WWDownloadStubs.cpp"
  "Core/Libraries/Source/WWVegas/WWDownload/registry.cpp"
  "Core/Libraries/Source/WWVegas/WWDownload/urlBuilder.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/seglinerenderer.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/composite.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/streakRender.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/CRC.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/ffactory.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/realcrc.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/thread.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/trim.cpp"
  "Core/GameEngine/Source/Common/GameUtility.cpp"
  "Core/Libraries/Source/WWVegas/WWMath/matrix3d.cpp"
  "Core/Libraries/Source/WWVegas/WWMath/matrix4.cpp"
  "Core/Libraries/Source/WWVegas/WWMath/quat.cpp"
  "Core/Libraries/Source/WWVegas/WWMath/wwmath.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/BitFlags.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/CommandLine.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/DamageFX.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Dict.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Language.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/GameLOD.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/GameMain.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INICommandSet.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIMapCache.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/MessageStream.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/NameKeyGenerator.cpp"
#  "GeneralsMD/Code/GameEngine/Source/Common/OptionPreferencesImplStub.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/PartitionSolver.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/AcademyStats.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/ActionManager.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/Energy.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/Handicap.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/Money.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/Player.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/PlayerList.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/PlayerTemplate.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/ProductionPrerequisite.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/Science.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/SpecialPower.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/WeaponSetUpgrade.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/Team.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/SkirmishBattleHonors.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/StateMachine.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/StatsCollector.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/System/DataChunk.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/System/DisabledTypes.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/System/FunctionLexicon.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/System/Geometry.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/System/KindOf.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/System/Trig.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/System/Upgrade.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Thing/MapObject.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Thing/Module.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Thing/ModuleFactory.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Thing/Thing.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Thing/ThingFactory.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Thing/ThingTemplate.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/WellKnownKeys.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/TerrainTypes.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/MultiplayerSettings.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/version.cpp"
#  "GeneralsMD/Code/GameEngine/Source/GameClient/CommandButton.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/Display.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/DisplayStringManager.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GameClient.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GameClientDispatch.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/Eva.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GlobalLanguage.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/LanguageFilter.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameFont.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowManager.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/Drawable/Update/BeaconClientUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/FXList.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/AnimateWindowManager.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarBeacon.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarCommand.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarCommandProcessing.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarMultiSelect.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarOCLTimer.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarObserver.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarPrintPositions.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarResizer.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarScheme.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarStructureInventory.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarUnderConstruction.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Shell/Shell.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/MessageBox.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/InGameChat.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/ClientInstance.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindow.cpp"
  "GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameWindow.cpp"
  "Core/GameEngine/Source/GameClient/GUI/WindowVideoManager.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetCheckBox.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetComboBox.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetListBox.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetProgressBar.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetPushButton.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetRadioButton.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetStaticText.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetTabControl.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetTextEntry.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetVerticalSlider.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Diplomacy.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ControlBarCallback.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/MainMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/CreditsMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ScoreScreen.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/MapSelectMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanLobbyMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanGameOptionsMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanMapSelectMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupHostGame.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupPlayerInfo.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupJoinGame.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DownloadMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLBuddyOverlay.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/SkirmishGameOptionsMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/HeaderTemplate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowTransitions.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ChallengeMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/QuitMenu.cpp"
  "GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/GUICallbacks/W3DMOTD.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/Color.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GameClient.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/Statistics.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/Credits.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameNetwork/GUIUtil.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameNetwork/GameSpyGP.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLobbyMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLoginMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLWelcomeMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLQuickMatchMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLGameSetupMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLMapSelectMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLMessageWindow.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLStatusMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLadderScreen.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLocaleSelectPopup.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLQMScoreScreen.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupReplay.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupSaveLoad.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupPlayerInfo.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupCommunicator.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupLadderSelect.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/GameInfoWindow.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DisconnectWindow.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/SinglePlayerMenu.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DifficultySelect.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ExtendedMessageBox.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/IMECandidate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/HotKey.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/HintSpy.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/Line2D.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/Input/Mouse.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/MetaEvent.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/RadiusDecal.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/System/Anim2D.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/System/RayEffect.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/System/CampaignManager.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/DrawGroupInfo.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GameText.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/System/Image.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AI.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIDock.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGroup.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGuard.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AISkirmishPlayer.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/AI/Squad.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/AI/TurretAI.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Map/PolygonTrigger.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Map/SidesList.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Map/TerrainLogic.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Armor.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/AutoHealBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BattleBusSlowDeathBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BehaviorModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeScaffoldBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeTowerBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BunkerBusterBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/CountermeasuresBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/FireWeaponWhenDamagedBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/FireWeaponWhenDeadBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/FlightDeckBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/GenerateMinefieldBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/GrantStealthBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/JetSlowDeathBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/MinefieldBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/NeutonBlastBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/OverchargeBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/ParkingPlaceBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/PoisonedBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/PrisonBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/PropagandaTowerBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/RebuildHoleBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/SlowDeathBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/SpawnBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/SupplyWarehouseCripplingBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/TechBuildingBehavior.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/ActiveBody.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/BodyModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/CrushDie.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/DamDie.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/DieModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/FXListDie.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/FiringTracker.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/ObjectDefectionHelper.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/ObjectHelper.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/ObjectRepulsorHelper.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/ObjectSMCHelper.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/ObjectWeaponStatusHelper.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/StatusDamageHelper.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/SubdualDamageHelper.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/TempWeaponBonusHelper.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Locomotor.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/ObjectCreationList.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/GhostObject.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/ObjectTypes.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/BaikonurLaunchPower.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/CleanupAreaPower.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/SpecialPowerModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/AssaultTransportAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/ChinookAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/DeliverPayloadAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/DeployStyleAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/DozerAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/HackInternetAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/JetAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/MissileAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/POWTruckAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/RailedTransportAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/RailroadGuideAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/SupplyTruckAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/TransportAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/WanderAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/WorkerAIUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AnimationSteeringUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AssistedTargetingUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AutoDepositUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AutoFindHealingUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BaseRenerateUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BattlePlanUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BoneFXUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/CheckpointUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/CleanupHazardUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/CommandButtonHuntUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DeletionUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DemoTrapUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DynamicGeometryInfoUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DynamicShroudClearingRangeUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/EMPUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/EnemyNearUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FireOCLAfterWeaponCooldownUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FireSpreadUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FireWeaponUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FirestormDynamicGeometryInfoUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FlammableUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/FloatUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/HeightDieUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/HelicopterSlowDeathUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/HijackerUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/HordeUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/LaserUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/LifetimeUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/MissileLauncherBuildingUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/MobMemberSlavedUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/NeutronMissileSlowDeathUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/NeutronMissileUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/OCLUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ParticleUplinkCannonUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PhysicsUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PilotFindVehicleUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PointDefenseLaserUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PowerPlantUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProductionUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProjectileStreamUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProneUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/RadarUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/RadiusDecalUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SlavedUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SmartBombTargetHomingUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpecialAbilityUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpecialPowerUpdateModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpectreGunshipDeploymentUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpectreGunshipUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpyVisionUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StealthDetectorUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StealthUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StickyBombUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StructureCollapseUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StructureToppleUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/TensileFormationUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ToppleUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/UpdateModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/WaveGuideUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/WeaponBonusUpdate.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ActiveShroudUpgrade.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ArmorUpgrade.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/CommandSetUpgrade.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/UpgradeModule.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/Object/WeaponSet.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptConditions.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptEngine.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/Scripts.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/VictoryConditions.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/System/CaveSystem.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/System/CrateSystem.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/System/Damage.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp"
  "Core/GameEngine/Source/GameNetwork/Network.cpp"
  "Core/GameEngine/Source/GameNetwork/NetworkUtil.cpp"
  "Core/GameEngine/Source/GameNetwork/LANAPI.cpp"
  "Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp"
  "Core/GameEngine/Source/GameNetwork/LANAPICallbacks.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameLogic/System/RankInfo.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8caps.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8fvf.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8indexbuffer.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8renderer.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8rendererdebugger.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8vertexbuffer.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/sortingrenderer.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/mapper.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/vertmaterial.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp"
  "Platform/MacOS/Source/Metal/MetalVertexBuffer8.mm"
  "Platform/MacOS/Source/Metal/MetalIndexBuffer8.mm"
#  "Platform/MacOS/Source/Main/MacOSRenderer.mm"  # Old MacOSRenderDevice pipeline — replaced by MetalDevice8
#  "Platform/MacOS/Source/Renderer/MacOSTexture.mm"  # Old MacOSTexture — replaced by MetalTexture8
  "Platform/MacOS/Source/Client/MacOSDisplayString.mm"
  "Platform/MacOS/Source/Client/MacOSDisplay.mm"
  "Platform/MacOS/Source/Main/MacOSWindowManager.mm"
  "Platform/MacOS/Source/Main/MacOSGameClient.mm"
  "Platform/MacOS/Source/Main/MacOSGameWindowManager.mm"
  "Platform/MacOS/Source/Main/MacOSGadgetDraw.mm"
  "Platform/MacOS/Source/Main/MacOSMain.mm"
  "Platform/MacOS/Source/Audio/MacOSAudioManager.mm"
  "Platform/MacOS/Source/Debug/MacOSScreenshot.mm"
  "Platform/MacOS/Source/Main/D3DXStubs.mm"
  "Platform/MacOS/Source/Metal/MetalDevice8.mm"
  "Platform/MacOS/Source/Metal/MetalInterface8.mm"
  "Platform/MacOS/Source/Metal/MetalSurface8.mm"
  "Platform/MacOS/Source/Metal/MetalTexture8.mm"
  "Platform/MacOS/Source/Stubs/GameSpyStubs.cpp"
  "Platform/MacOS/Source/Stubs/LZHLStubs.cpp"
  "Platform/MacOS/Source/Stubs/GitInfoStubs.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshmatdesc.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/pipe.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/base64.cpp"
  "GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshgeometry.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/b64pipe.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/b64straw.cpp"
  "GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DFunctionLexicon.cpp"
  "GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DInGameUI.cpp"
  "GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/GUICallbacks/W3DMainMenu.cpp"
  "GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/GUICallbacks/W3DControlBar.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/xpipe.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/cstraw.cpp"
  "Core/Libraries/Source/WWVegas/WWMath/tri.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/RTS/TunnelTracker.cpp"
  "GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShroud.cpp"
  "Core/GameEngine/Source/GameNetwork/Transport.cpp"
  "Core/GameEngineDevice/Source/W3DDevice/GameClient/WorldHeightMap.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Bezier/BezierSegment.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/matpass.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/w3dexclusionlist.cpp"
  "Core/Libraries/Source/WWVegas/WW3D2/texture.cpp"
  "GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DPoly.cpp"
  "Core/GameEngine/Source/GameNetwork/NetCommandMsg.cpp"
  "Core/GameEngineDevice/Source/W3DDevice/GameClient/TileData.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/Bezier/BezFwdIterator.cpp"
  "Core/Libraries/Source/WWVegas/WWMath/matrix3.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/buff.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/xstraw.cpp"
  "Core/Libraries/Source/WWVegas/WWLib/targa.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp"
  "Core/GameEngine/Source/Common/AddonCompat.cpp"
  "Core/GameEngine/Source/GameNetwork/NAT.cpp"
  "Core/GameEngine/Source/GameNetwork/udp.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIAiData.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIAnimation.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INICommandButton.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INICommandSet.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIControlBarScheme.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INICrate.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIDamageFX.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIDrawGroupInfo.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIGameData.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIMapCache.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIMapData.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIMappedImage.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIModel.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIMultiplayer.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIObject.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIParticleSys.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INISpecialPower.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INITerrain.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INITerrainBridge.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INITerrainRoad.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIUpgrade.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIWater.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIWeapon.cpp"
  "GeneralsMD/Code/GameEngine/Source/Common/INI/INIWebpageURL.cpp"
  "Core/GameEngine/Source/Common/INI/INIAudioEventInfo.cpp"
  "Core/GameEngine/Source/Common/INI/INIMiscAudio.cpp"
  "Core/GameEngine/Source/Common/INI/INIVideo.cpp"
  "Core/GameEngine/Source/GameNetwork/GameSpy/Chat.cpp"
  "GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Shell/ShellMenuScheme.cpp"
)

# Bulk additions for modules
SOURCES+=(
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProductionExitUpdate/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Destroy/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SpecialPower/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Helper/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Damage/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/Drawable/Update/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowTransitionsStyles.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowTransitions.cpp
  Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DTerrainTracks.cpp
  Core/GameEngineDevice/Source/W3DDevice/GameClient/TerrainTex.cpp
  Core/Libraries/Source/WWVegas/WW3D2/predlod.cpp
  Core/Libraries/Source/WWVegas/WW3D2/distlod.cpp
  Core/Libraries/Source/WWVegas/WW3D2/static_sort_list.cpp
  Core/Libraries/Source/WWVegas/WW3D2/coltest.cpp
  Core/Libraries/Source/WWVegas/WW3D2/dx8polygonrenderer.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/EstablishConnectionsMenu/EstablishConnectionsMenu.cpp
  GeneralsMD/Code/GameEngine/Source/Common/RTS/ResourceGatheringManager.cpp
  Core/Libraries/Source/WWVegas/WWLib/hash.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/LoadScreen.cpp
  Core/Libraries/Source/WWVegas/WW3D2/render2dsentence.cpp
  Core/Libraries/Source/WWVegas/WW3D2/texturethumbnail.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/lightenvironment.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ddsfile.cpp
  Core/Libraries/Source/WWVegas/WW3D2/animatedsoundmgr.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hanimmgr.cpp
  Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DTerrainBackground.cpp
  Core/Libraries/Source/WWVegas/WW3D2/hcanim.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SimpleObjectIterator.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/GUICommandTranslator.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/PlaceEventTranslator.cpp
  Core/Libraries/Source/WWVegas/WW3D2/stripoptimizer.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/saveload.cpp
  Core/Libraries/Source/WWVegas/WW3D2/textureloader.cpp
  Core/Libraries/Source/WWVegas/WW3D2/metalmap.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/motchan.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/persistfactory.cpp
  Core/Libraries/Source/WWVegas/WWLib/FastAllocator.cpp
  Core/GameEngine/Source/GameNetwork/FirewallHelper.cpp
  Core/Libraries/Source/WWVegas/WW3D2/font3d.cpp
  Core/Libraries/Source/WWVegas/WWLib/rawfile.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/aabtreebuilder.cpp
  Core/Libraries/Source/WWVegas/WW3D2/decalsys.cpp
  Core/Libraries/Source/WWVegas/WW3D2/visrasterizer.cpp
  Core/Libraries/Source/WWVegas/WW3D2/projector.cpp
  Core/Libraries/Source/WWVegas/WW3D2/texturefilter.cpp
  Core/Libraries/Source/WWVegas/WW3D2/bitmaphandler.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3dWaypointBuffer.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp
  Core/Libraries/Source/WWVegas/WW3D2/segline.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/pointerremap.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/htreemgr.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/matrixmapper.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameWindowManager.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowGlobal.cpp
  Core/GameEngine/Source/GameNetwork/GameMessageParser.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowManagerScript.cpp
  Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp
  Core/GameEngine/Source/GameNetwork/Connection.cpp
  Core/GameEngine/Source/GameNetwork/DisconnectManager.cpp
  Core/GameEngine/Source/GameNetwork/udp.cpp
  Core/GameEngine/Source/GameNetwork/NetPacket.cpp
  Core/GameEngine/Source/GameNetwork/NetCommandList.cpp
  Core/GameEngine/Source/GameNetwork/NetCommandMsg.cpp
  Core/GameEngine/Source/GameNetwork/FrameData.cpp
  Core/GameEngine/Source/GameNetwork/FrameDataManager.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
  Core/GameEngine/Source/GameNetwork/NetCommandWrapperList.cpp
  Core/GameEngine/Source/GameNetwork/User.cpp
  Core/GameEngine/Source/GameNetwork/GameInfo.cpp
  Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp
  Core/GameEngine/Source/Common/ReplaySimulation.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DShadow.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DVolumetricShadow.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp
  Core/GameEngine/Source/Common/WorkerProcess.cpp
  Core/GameEngine/Source/Common/RandomValue.cpp
  Core/GameEngine/Source/Common/crc.cpp
  Core/GameEngine/Source/Common/CRCDebug.cpp
  Core/GameEngine/Source/Common/FramePacer.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/WindowXlat.cpp
  Core/Libraries/Source/WWVegas/WWLib/bufffile.cpp
  Core/Libraries/Source/WWVegas/WWLib/buff.cpp
  Core/GameEngine/Source/Common/FrameRateLimit.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DRoadBuffer.cpp
  Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DTreeBuffer.cpp
  Core/Libraries/Source/WWVegas/WWLib/chunkio.cpp
  GeneralsMD/Code/GameEngine/Source/Common/DiscreteCircle.cpp
  Core/Libraries/Source/WWVegas/WW3D2/missingtexture.cpp
  Core/Libraries/Source/WWVegas/WW3D2/font3d.cpp
  Core/Libraries/Source/WWVegas/WWLib/widestring.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/WinInstanceData.cpp
  Core/Libraries/Source/WWVegas/WW3D2/assetstatus.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/saveload.cpp
  Core/Libraries/Source/WWVegas/WW3D2/stripoptimizer.cpp
  Core/Libraries/Source/WWVegas/WW3D2/metalmap.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshmdl.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshmdlio.cpp
  Core/Libraries/Source/WWVegas/WW3D2/pointgr.cpp
  Core/Libraries/Source/WWVegas/WW3D2/snappts.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DBridgeBuffer.cpp
  Core/Libraries/Source/WWVegas/WW3D2/w3d_util.cpp
  Core/Libraries/Source/WWVegas/WWLib/FastAllocator.cpp
  Core/Libraries/Source/WWVegas/WW3D2/statistics.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/DisconnectMenu/DisconnectMenu.cpp
  Core/Libraries/Source/WWVegas/WWLib/cpudetect.cpp
  Core/Libraries/Source/WWVegas/WW3D2/matinfo.cpp
  Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DModelDraw.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/SimpleObjectIterator.cpp
  Core/Libraries/Source/WWVegas/WW3D2/textureloader.cpp
  GeneralsMD/Code/GameEngine/Source/Common/Thing/DrawModule.cpp
  Core/Libraries/Source/WWVegas/WW3D2/texproject.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DAssetManager.cpp
  Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DPropBuffer.cpp
  GeneralsMD/Code/GameEngine/Source/Common/INI/INIWebpageURL.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/saveloadstatus.cpp
  Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DSnow.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hmorphanim.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/registry.cpp
  Core/Libraries/Source/WWVegas/WW3D2/shattersystem.cpp
  Core/Libraries/Source/WWVegas/WWLib/textfile.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hlod.cpp
  Core/GameEngine/Source/GameNetwork/WOLBrowser/WebBrowser.cpp
  Core/Libraries/Source/WWVegas/WWLib/registry.cpp
  Core/Libraries/Source/WWVegas/WW3D2/dynamesh.cpp
  Core/GameEngine/Source/GameNetwork/IPEnumeration.cpp
  Core/GameEngine/Source/GameNetwork/NetCommandRef.cpp
  Core/GameEngine/Source/GameNetwork/GameSpy/Thread/BuddyThread.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGroup.cpp
  Core/GameEngine/Source/Common/UserPreferences.cpp
  GeneralsMD/Code/GameEngine/Source/Common/RTS/Team.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/WindowLayout.cpp
  Core/Libraries/Source/WWVegas/WW3D2/bwrender.cpp
  Core/Libraries/Source/WWVegas/WW3D2/dx8webbrowser.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hrawanim.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hanimmgr.cpp
  Core/Libraries/Source/WWVegas/WW3D2/texture.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DBibBuffer.cpp
  Core/Libraries/Source/WWVegas/WWLib/slnode.cpp
  Core/Libraries/Source/WWVegas/WW3D2/font3d.cpp
  Core/Libraries/Source/WWVegas/WW3D2/render2dsentence.cpp
  Core/Libraries/Source/WWVegas/WW3D2/surfaceclass.cpp
  GeneralsMD/Code/GameEngine/Source/Common/RTS/MissionStats.cpp
  Core/Libraries/Source/WWVegas/WWLib/random.cpp
  Core/Libraries/Source/WWVegas/WW3D2/seglinerenderer.cpp
  Core/Libraries/Source/WWVegas/WW3D2/streakRender.cpp
  Core/GameEngine/Source/GameNetwork/FrameMetrics.cpp
  Core/Libraries/Source/WWVegas/WW3D2/aabtree.cpp
  Core/Libraries/Source/WWVegas/WWLib/DbgHelpGuard.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
  Core/Libraries/Source/WWVegas/WWLib/DbgHelpLoader.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DFileSystem.cpp
  Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DVideoBuffer.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDebugDisplay.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDynamicLight.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DStatusCircle.cpp
  Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp
  Core/GameEngineDevice/Source/W3DDevice/GameClient/CameraShakeSystem.cpp
  Core/GameEngine/Source/GameClient/ParabolicEase.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/System/DebugDisplay.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
  Core/Libraries/Source/WWVegas/WW3D2/pivot.cpp
  Core/Libraries/Source/WWVegas/WW3D2/htree.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ControlBarPopupDescription.cpp
  Core/Libraries/Source/WWVegas/WWLib/readline.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/EstablishConnectionsWindow.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DVerticalSlider.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DHorizontalSlider.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DCheckBox.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DListBox.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DRadioButton.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DTextEntry.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DComboBox.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DProgressBar.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DStaticText.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DPushButton.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/Gadget/W3DTabControl.cpp
  Core/Libraries/Source/WWVegas/WWLib/nstrdup.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/W3DConvert.cpp
  Core/GameEngine/Source/GameNetwork/GameSpy/LobbyUtils.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/QuotedPrintable.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/NetworkDirectConnect.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLCustomScoreScreen.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/SkirmishMapSelectMenu.cpp
  Core/Libraries/Source/WWVegas/WW3D2/formconv.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/InGamePopupMessage.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/KeyboardOptionsMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/IMEManager.cpp
  GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/GeneralsExpPoints.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DParticleSys.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/encrypt.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DAssetManagerExposed.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ReplayControls.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/twiddler.cpp
  Core/Libraries/Source/WWVegas/WWLib/gcd_lcm.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/definition.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/definitionmgr.cpp
  Core/Libraries/Source/WWVegas/WW3D2/streak.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/definitionfactory.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/definitionfactorymgr.cpp
  Core/Libraries/Source/WWVegas/WWSaveLoad/saveloadsubsystem.cpp
  Core/Libraries/Source/WWVegas/WW3D2/ringobj.cpp
  Core/Libraries/Source/WWVegas/WW3D2/sphereobj.cpp
  Core/GameEngine/Source/Common/System/Debug.cpp
  Core/Libraries/Source/WWVegas/WWLib/refcount.cpp
  GeneralsMD/Code/GameEngine/Source/Common/MiniLog.cpp
  GeneralsMD/Code/GameEngine/Source/Common/PerfTimer.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDebugIcons.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/StackDump.cpp
  Core/GameEngine/Source/GameClient/System/Debug/AudioDebugDisplay.cpp
)

# Bulk additions for AI and Math
SOURCES+=(
  GeneralsMD/Code/GameEngine/Source/GameLogic/AI/*.cpp
  Core/Libraries/Source/WWVegas/WWMath/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/*.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/*.cpp
)

SOURCES+=("GeneralsMD/Code/GameEngine/Source/Common/System/CriticalSection.cpp")
SOURCES+=("GeneralsMD/Code/GameEngine/Source/GameClient/DisplayString.cpp")
SOURCES+=("GeneralsMD/Code/GameEngine/Source/GameClient/DisplayStringManager.cpp")
SOURCES+=("Platform/MacOS/Source/MacOSGameEngineHooks.cpp")


# Deduplicate sources
SOURCES=($(printf "%s\n" "${SOURCES[@]}" | sort -u))
