if(NOT EXISTS "${GAME}" OR NOT EXISTS "${PDB}")
    # The pre-link runtime deployment runs before the first executable exists.
    return()
endif()
execute_process(COMMAND "${GIT}" -C "${SOURCE}" rev-parse HEAD OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${GIT}" -C "${SOURCE}" status --porcelain OUTPUT_VARIABLE status COMMAND_ERROR_IS_FATAL ANY)
set(dirty false)
if(NOT status STREQUAL "")
    set(dirty true)
endif()
set(document "{}")
string(JSON document SET "${document}" revision "\"${revision}\"")
string(JSON document SET "${document}" dirty ${dirty})
string(JSON document SET "${document}" compiler "\"${COMPILER}\"")
string(JSON document SET "${document}" configuration "\"${CONFIG}\"")
string(JSON document SET "${document}" architecture "\"x86\"")
string(JSON document SET "${document}" backend "\"crashpad\"")
string(JSON document SET "${document}" crashpad_revision "\"7e0af1d4d45b526f01677e74a56f4a951b70517d\"")
string(JSON document SET "${document}" vcpkg_baseline "\"b02e341c927f16d991edbd915d8ea43eac52096c\"")
string(JSON document SET "${document}" package_triplet "\"x86-windows-static-md\"")
string(JSON document SET "${document}" handler_configuration "\"Release\"")
foreach(kind GAME PDB BRIDGE BRIDGE_PDB HANDLER)
    file(SHA256 "${${kind}}" hash)
    get_filename_component(name "${${kind}}" NAME)
    string(JSON document SET "${document}" "${kind}" "{\"file\":\"${name}\",\"sha256\":\"${hash}\"}")
endforeach()
file(WRITE "${OUTPUT}" "${document}\n")
