# ICU4C for the engine.
#
# Preference order:
# 1. find_package(ICU) from vcpkg or the system (C + C++ APIs: uc, i18n, data)
# 2. Windows SDK icu.lib for modern MSVC (C API: common + i18n via <icu.h>)
# 3. Runtime LoadLibrary of OS icu.dll (VC6 and other Windows toolchains without an import lib)
#
# VC6 uses ICU UTF conversion exports through IcuLoader, without ICU headers or import libraries.
# If the DLL or either export is missing, conversion falls back to Win32 CP_UTF8.

add_library(core_icu STATIC)

set(RTS_ICU_LINKED FALSE)
set(RTS_ICU_CXX FALSE)
set(RTS_ICU_I18N FALSE)
set(RTS_ICU_WINSDK FALSE)
set(RTS_ICU_DYNAMIC FALSE)

if(NOT IS_VS6_BUILD)
    find_package(ICU QUIET COMPONENTS uc i18n data)
    if(NOT ICU_FOUND)
        find_package(ICU QUIET COMPONENTS uc i18n)
    endif()
    if(NOT ICU_FOUND)
        find_package(ICU QUIET COMPONENTS uc data)
    endif()
    if(NOT ICU_FOUND)
        find_package(ICU QUIET COMPONENTS uc)
    endif()
endif()

if(ICU_FOUND AND NOT IS_VS6_BUILD)
    set(RTS_ICU_LINKED TRUE)
    set(RTS_ICU_CXX TRUE)
    target_link_libraries(core_icu PUBLIC ICU::uc)
    if(TARGET ICU::i18n)
        set(RTS_ICU_I18N TRUE)
        target_link_libraries(core_icu PUBLIC ICU::i18n)
    endif()
    if(TARGET ICU::data)
        target_link_libraries(core_icu PUBLIC ICU::data)
    endif()
    target_compile_definitions(core_icu PUBLIC RTS_HAS_ICU RTS_HAS_ICU_CXX)
    if(RTS_ICU_I18N)
        target_compile_definitions(core_icu PUBLIC RTS_HAS_ICU_I18N)
    endif()
    message(STATUS "ICU4C: linked via find_package (C++ API enabled)")
elseif(WIN32 AND NOT IS_VS6_BUILD AND NOT MINGW)
    find_library(RTS_ICU_WINSDK_LIB NAMES icu)
    if(RTS_ICU_WINSDK_LIB)
        set(RTS_ICU_LINKED TRUE)
        set(RTS_ICU_I18N TRUE)
        set(RTS_ICU_WINSDK TRUE)
        target_link_libraries(core_icu PUBLIC ${RTS_ICU_WINSDK_LIB} delayimp)
        target_link_options(core_icu PUBLIC "/DELAYLOAD:icu.dll")
        target_compile_definitions(core_icu PUBLIC RTS_HAS_ICU RTS_HAS_ICU_WINSDK RTS_HAS_ICU_I18N)
        message(STATUS "ICU4C: linked via Windows SDK (${RTS_ICU_WINSDK_LIB})")
    endif()
endif()

if(NOT RTS_ICU_LINKED)
    if(WIN32)
        set(RTS_ICU_DYNAMIC TRUE)
        target_compile_definitions(core_icu PUBLIC RTS_ICU_DYNAMIC)
        message(STATUS "ICU4C: IcuLoader resolves UTF conversion exports from icu.dll; Win32 fallback if unavailable")
    else()
        message(FATAL_ERROR "ICU4C is required on non-Windows platforms. Install libicu or enable vcpkg.")
    endif()
endif()

add_feature_info(IcuLinked RTS_ICU_LINKED "Link ICU4C into the engine")
add_feature_info(IcuCxx RTS_ICU_CXX "ICU C++ API available")
add_feature_info(IcuI18n RTS_ICU_I18N "ICU i18n API available")
add_feature_info(IcuWinSdk RTS_ICU_WINSDK "Windows SDK ICU C API")
add_feature_info(IcuDynamic RTS_ICU_DYNAMIC "Load OS icu.dll at runtime")
